packages:
  - packages/libs/*
  - packages/apps/*
onlyBuiltDependencies:
  - '@sentry/cli'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - bufferutil
  - bun
  - core-js
  - esbuild
  - fsevents
  - keccak
  - mongodb-memory-server
  - nx
  - protobufjs
  - unrs-resolver
  - utf-8-validate
overrides:
  typescript: 5.8.3
