const fs = require('fs');
const path = require('path');

const esbuild = require('esbuild');
const { polyfillNode } = require('esbuild-plugin-polyfill-node');
const Hash = require('ipfs-only-hash');

/**
 * Creates a plugin to alias fetch implementations to a shim
 * @param {string} shimPath - Path to the fetch shim
 * @returns {object} esbuild plugin
 */
function aliasFetch(shimPath) {
  return {
    name: 'alias-fetch',
    setup(build) {
      build.onResolve({ filter: /^node-fetch$/ }, () => ({ path: shimPath }));
      build.onResolve({ filter: /^cross-fetch(\/.*)?$/ }, () => ({ path: shimPath }));
    },
  };
}

/**
 * Ensures a directory exists
 * @param {string} filePath - Path to the file
 */
const ensureDirectoryExistence = (filePath) => {
  const dirname = path.dirname(filePath);
  if (!fs.existsSync(dirname)) {
    fs.mkdirSync(dirname, { recursive: true });
  }
};

/**
 * Gets the bundled Vincent tool code
 * @param {string} ipfsCid - The IPFS CID of the tool
 * @param {string} vincentToolPath - Path to the vincent-tool
 * @returns {string} The bundled tool code
 */
function getBundledVincentToolCode(ipfsCid, vincentToolPath) {
  return `/**
* DO NOT EDIT THIS FILE. IT IS GENERATED ON BUILD.
*/

import { asBundledVincentTool } from '@lit-protocol/vincent-tool-sdk';
import { vincentTool } from '${vincentToolPath}';

export const bundledVincentTool = asBundledVincentTool(vincentTool, "${ipfsCid}");
`;
}

/**
 * Creates the Lit Action module code
 * @param {object} params - Parameters
 * @param {string} params.ipfsCid - The IPFS CID
 * @param {string} params.content - The content
 * @returns {string} The Lit Action module code
 */
function litActionModuleCode({ ipfsCid, content }) {
  return `/**
* DO NOT EDIT THIS FILE. IT IS GENERATED ON BUILD.
* @type {string}
*/
const code = ${JSON.stringify(content)};
module.exports = {
  "code": code,
  "ipfsCid": "${ipfsCid}",
};
`;
}

/**
 * Creates the metadata JSON file
 * @param {object} params - Parameters
 * @param {string} params.ipfsCid - The IPFS CID
 * @returns {string} The metadata JSON
 */
function metadataJsonFile({ ipfsCid }) {
  return `{
  "ipfsCid": "${ipfsCid}"
}
`;
}

/**
 * Creates a plugin to create the bundled tool file
 * @param {string} sourceDir - The source directory
 * @returns {object} esbuild plugin
 */
function createBundledToolFile(sourceDir) {
  return {
    name: 'create-vincent-bundled-tool-file',
    setup(build) {
      build.initialOptions.write = false;

      build.onEnd(async (result) => {
        if (result.errors.length > 0) {
          console.error('Build failed with errors:', result.errors);
          return;
        }

        const outputFile = result.outputFiles[0];
        const content = outputFile.text;
        const ipfsCid = await Hash.of(content);

        // Write bundledTool wrapper
        // Get the output directory path
        const outputPath = path.dirname(path.resolve(outputFile.path));
        // Calculate the relative path from the output directory to the source directory
        const relativePathToSourceDir = path.relative(outputPath, sourceDir);
        // Construct the path to the vincent-tool.ts file relative to the output directory
        const vincentToolPath = path.join(relativePathToSourceDir, 'vincent-tool');
        // Generate the bundled source code with the computed relative path
        const bundledSource = getBundledVincentToolCode(ipfsCid, vincentToolPath);

        // Use the output path to determine the bundled tool path
        const bundledPath = path.join(outputPath, 'vincent-bundled-tool.ts');

        ensureDirectoryExistence(bundledPath);
        fs.writeFileSync(bundledPath, bundledSource);

        // Write metadata JSON
        // Use the directory of the generated output file

        const metadataPath = path.join(outputPath, 'vincent-tool-metadata.json');
        const metadataContent = metadataJsonFile({ ipfsCid });
        ensureDirectoryExistence(metadataPath);
        fs.writeFileSync(metadataPath, metadataContent);
      });
    },
  };
}

/**
 * Creates a plugin to wrap IIFE in string
 * @returns {object} esbuild plugin
 */
const wrapIIFEInStringPlugin = {
  name: 'wrap-iife-in-string',
  setup(build) {
    build.initialOptions.write = false;

    build.onEnd(async (result) => {
      if (result.errors.length > 0) {
        console.error('Build failed with errors:', result.errors);
        return;
      }

      const outputFile = result.outputFiles[0];
      const content = outputFile.text;
      const ipfsCid = await Hash.of(content);

      const wrapped = litActionModuleCode({ content, ipfsCid });

      // Use the path from the generated output file
      const outputPath = path.resolve(outputFile.path);

      ensureDirectoryExistence(outputPath);
      fs.writeFileSync(outputPath, wrapped);
    });
  },
};

/**
 * Builds a Vincent tool
 * @param {object} options - Build options
 * @param {string} options.entryPoint - The entry point file
 * @param {string} options.outdir - The output directory
 * @param {string} options.tsconfigPath - Path to tsconfig.json
 * @returns {Promise<void>}
 */
async function buildVincentTool({ entryPoint, outdir, tsconfigPath }) {
  try {
    const sourceDir = path.dirname(entryPoint);

    await esbuild
      .build({
        outdir,
        tsconfig: tsconfigPath,
        entryPoints: [entryPoint],
        bundle: true,
        minify: false,
        sourcemap: false,
        treeShaking: true,
        metafile: true,
        plugins: [
          aliasFetch(path.resolve(__dirname, 'deno-fetch-shim.js')),
          polyfillNode({
            globals: {
              Buffer: true,
              process: true,
            },
            modules: {
              crypto: true,
              http: true,
              https: true,
              stream: true,
              zlib: true,
              url: true,
              util: true,
            },
          }),
          wrapIIFEInStringPlugin,
          createBundledToolFile(sourceDir),
        ],
        platform: 'browser',
        write: false,
      })
      .then((result) => {
        result.outputFiles.forEach((file) => {
          const bytes = file.text.length;
          const mbInBinary = (bytes / (1024 * 1024)).toFixed(4);
          const mbInDecimal = (bytes / 1_000_000).toFixed(4);

          console.log(
            `✅ ${file.path.split('/').pop()}\n- ${mbInDecimal} MB (in decimal)\n- ${mbInBinary} MB (in binary)`,
          );
        });
      });

    console.log('✅ Vincent tool built successfully');
  } catch (e) {
    console.error('❌ Error building Vincent tool: ', e);
    throw e;
  }
}

/**
 * Example usage:
 *
 * // Build with output directory
 * buildVincentTool({
 *   entryPoint: './src/lib/failure-tools/bothFailWithSchema/lit-action.ts',
 *   outdir: './dist/'
 * });
 */
module.exports = {
  buildVincentTool,
};
