/**
 * DO NOT EDIT THIS FILE. IT IS GENERATED ON BUILD.
 */

import { asBundledVincentPolicy } from '@lit-protocol/vincent-tool-sdk';
import { vincentPolicy } from './vincent-policy';

export const bundledVincentPolicy = asBundledVincentPolicy(
  vincentPolicy,
  'QmahYzajtKhyZqt32GZTEyTVudwYF5cphJakzn6dYc1Q44' as const,
);
