/**
 * DO NOT EDIT THIS FILE. IT IS GENERATED ON BUILD.
 */

import { asBundledVincentPolicy } from '@lit-protocol/vincent-tool-sdk';
import { vincentPolicy } from './vincent-policy';

export const bundledVincentPolicy = asBundledVincentPolicy(
  vincentPolicy,
  'QmVr6x9XWsJSxAr3Kt1VCN3wrMNyaEawSuM2N1t1rtQDza' as const,
);
