const fs = require('fs');
const path = require('path');

const esbuild = require('esbuild');
const { polyfillNode } = require('@lit-protocol/esbuild-plugin-polyfill-node');
const Hash = require('ipfs-only-hash');

function aliasFetch() {
  const shim = path.resolve(__dirname, 'deno-fetch-shim.js');

  return {
    name: 'alias-fetch',
    setup(build) {
      build.onResolve({ filter: /^node-fetch$/ }, () => ({ path: shim }));
      build.onResolve({ filter: /^cross-fetch(\/.*)?$/ }, () => ({ path: shim }));
    },
  };
}

const ensureDirectoryExistence = (filePath) => {
  const dirname = path.dirname(filePath);
  if (!fs.existsSync(dirname)) {
    fs.mkdirSync(dirname, { recursive: true });
  }
};

function getBundledVincentAbilityCode() {
  return `/**
 * DO NOT EDIT THIS FILE. IT IS GENERATED ON BUILD.
 */

import { asBundledVincentAbility } from '@lit-protocol/vincent-ability-sdk';
import { vincentAbility } from '../lib/vincent-ability';
import metadata from './vincent-ability-metadata.json';

if(!metadata.ipfsCid) {
  throw new Error('ipfsCid is not defined in metadata JSON file');
}

export const bundledVincentAbility = asBundledVincentAbility(vincentAbility, metadata.ipfsCid);
`;
}

function litActionModuleCode({ ipfsCid, content }) {
  return `/**
 * DO NOT EDIT THIS FILE. IT IS GENERATED ON BUILD.
 * @type {string}
 */
const code = ${JSON.stringify(content)};
module.exports = {
  "code": code,
  "ipfsCid": "${ipfsCid}",
};
`;
}

function metadataJsonFile({ ipfsCid }) {
  return `{
  "ipfsCid": "${ipfsCid}"
}
`;
}

function createOrUpdatePrepareMetadata({ ipfsCid, metadataPath }) {
  let existingMetadata = {};

  if (fs.existsSync(metadataPath)) {
    const existingContent = fs.readFileSync(metadataPath, 'utf8');
    existingMetadata = JSON.parse(existingContent);
  }

  // Update only the ipfsCid, preserve everything else if exists (e.g. PKP info)
  const updatedMetadata = {
    ...existingMetadata,
    ipfsCid: ipfsCid,
  };

  return JSON.stringify(updatedMetadata, null, 2);
}

const createBundledAbilityFile = {
  name: 'create-vincent-bundled-ability-file',
  setup(build) {
    build.initialOptions.write = false;

    const sourceDir = path.dirname(build.initialOptions.entryPoints[0]);

    console.log(sourceDir);
    build.onEnd(async (result) => {
      if (result.errors.length > 0) {
        console.error('Build failed with errors:', result.errors);
        return;
      }

      const outputFile = result.outputFiles[0];
      const content = outputFile.text;
      const ipfsCid = await Hash.of(content);

      // Write bundledAbility wrapper
      const bundledSource = getBundledVincentAbilityCode();
      const bundledPath = path.join(sourceDir, '../generated/vincent-bundled-ability.ts');
      fs.writeFileSync(bundledPath, bundledSource);

      // Write metadata JSON
      const outputPath = path.dirname(path.resolve(outputFile.path));
      const metadataPath = path.join(outputPath, 'vincent-ability-metadata.json');
      const metadataContent = metadataJsonFile({ ipfsCid });
      fs.writeFileSync(metadataPath, metadataContent);
    });
  },
};

const wrapIIFEInStringPlugin = {
  name: 'wrap-iife-in-string',
  setup(build) {
    build.initialOptions.write = false;

    build.onEnd(async (result) => {
      if (result.errors.length > 0) {
        console.error('Build failed with errors:', result.errors);
        return;
      }

      const outputFile = result.outputFiles[0];
      const content = outputFile.text;
      const ipfsCid = await Hash.of(content);

      const wrapped = litActionModuleCode({ content, ipfsCid });
      const outputPath = path.resolve(outputFile.path);
      ensureDirectoryExistence(outputPath);
      fs.writeFileSync(outputPath, wrapped);
    });
  },
};

(async () => {
  try {
    const sharedConfig = {
      tsconfig: './tsconfig.lib.json',
      bundle: true,
      minify: false,
      sourcemap: false,
      treeShaking: true,
      metafile: true,
      outdir: './src/generated/',
      platform: 'browser',
      write: false,
    };

    await esbuild
      .build({
        ...sharedConfig,
        entryPoints: ['./src/lib/lit-action.ts'],
        plugins: [
          aliasFetch(),
          polyfillNode({
            globals: {
              Buffer: true,
              process: true,
            },
            modules: {
              crypto: true,
              http: true,
              https: true,
              stream: true,
              zlib: true,
              url: true,
              util: true,
            },
          }),
          wrapIIFEInStringPlugin,
          createBundledAbilityFile,
        ],
      })
      .then((result) => {
        result.outputFiles.forEach((file) => {
          const bytes = file.text.length;
          const mbInBinary = (bytes / (1024 * 1024)).toFixed(4);
          const mbInDecimal = (bytes / 1_000_000).toFixed(4);

          console.log(
            `✅ ${file.path.split('/').pop()}\n- ${mbInDecimal} MB (in decimal)\n- ${mbInBinary} MB (in binary)`,
          );
        });
      });

    console.log('✅ Vincent ability built successfully');

    await esbuild
      .build({
        ...sharedConfig,
        entryPoints: ['./src/lib/prepare/lit-action.ts'],
        plugins: [
          aliasFetch(),
          polyfillNode({
            globals: {
              Buffer: true,
              process: true,
            },
            modules: {
              crypto: true,
              http: true,
              https: true,
              stream: true,
              zlib: true,
              url: true,
              util: true,
            },
          }),
          {
            name: 'wrap-prepare-iife-in-string',
            setup(build) {
              build.initialOptions.write = false;

              build.onEnd(async (result) => {
                if (result.errors.length > 0) {
                  console.error('Build failed with errors:', result.errors);
                  return;
                }

                const outputFile = result.outputFiles[0];
                const content = outputFile.text;
                const ipfsCid = await Hash.of(content);

                const wrapped = litActionModuleCode({ content, ipfsCid });
                const outputPath = path.resolve('./src/generated/lit-action-prepare.js');
                ensureDirectoryExistence(outputPath);
                fs.writeFileSync(outputPath, wrapped);

                const metadataPath = path.resolve('./src/generated/vincent-prepare-metadata.json');
                const metadataContent = createOrUpdatePrepareMetadata({ ipfsCid, metadataPath });
                fs.writeFileSync(metadataPath, metadataContent);
              });
            },
          },
        ],
      })
      .then((result) => {
        result.outputFiles.forEach((file) => {
          const bytes = file.text.length;
          const mbInBinary = (bytes / (1024 * 1024)).toFixed(4);
          const mbInDecimal = (bytes / 1_000_000).toFixed(4);

          console.log(
            `✅ prepare-${file.path.split('/').pop()}\n- ${mbInDecimal} MB (in decimal)\n- ${mbInBinary} MB (in binary)`,
          );
        });
      });

    console.log('✅ All lit actions built successfully');
  } catch (e) {
    console.error('❌ Error building lit actions: ', e);
    process.exit(1);
  }
})();
